### PR TITLE
fix image issue

### PR DESCRIPTION
**Pull request by sthsuyash**
### **fix placeholder image on frontend**

add placeholder image for items with no image.

image

### CODE REVIEW

**Comment by vanessa-cooper** [comment]
Thanks sthsuyash, I'll review the changes right away!

**Review by vanessa-cooper — CHANGES_REQUESTED** [review]
Make sure all checks pass, only then you can merge the PR.

**Review by vanessa-cooper — APPROVED** [review]
Excellent job sthsuyash! You're now able to merge the PR.

**Review by vanessa-cooper — CHANGES_REQUESTED** [review]
Make sure all checks pass, only then you can merge the PR.

**Comment by sthsuyash** [comment]
fixed the issue

**Review by vanessa-cooper — APPROVED** [review]
Excellent job sthsuyash! You're now able to merge the PR.

**Pull request merged**
